name: Docker Hub Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: scottlewis193/f1-league:latest
          build-args: |
            PUBLIC_PB_URL=https://pb-f1-league.hades.ws
            PUBLIC_VAPID_PUBLIC_KEY=BHKr-fL3KUrgDknbDc0-N3vbrZtMOwf3to5yM0NLbmsLMyil3EcmdPzRA-ZfP83YxDPgU5XcAiMHTpk7LKQ26Uo
